### ISSUE TITLE
Problem with running Model_Analysis

### ISSUE THREAD

**Issue by utipe** [cooperlab/SurvivalNet#31]
Hi,

Thank you for sharing your code. I'm having a problem with running the Model_Analysis script. For certain dataset (subgroups of variables), I can run Model_Analysis with no issue. However, for other subset of variables, I encountered the following error:

> Generting risk gradient profiles...
Traceback (most recent call last):
  File "ModelAnalysis.py", line 43, in <module>
    Tau=5e-2, Path=Path)
  File "/home/an/python2/SurvivalNet/survivalnet/analysis/FeatureAnalysis.py", line 67, in FeatureAnalysis
    Gradients = RiskCohort(Model, Normalized)
  File "/home/an/python2/SurvivalNet/survivalnet/analysis/RiskCohort.py", line 44, in RiskCohort
    Gradients[i, :] = _RiskBackpropagate(Model, Matrix[i, :])
  File "/home/an/python2/SurvivalNet/survivalnet/analysis/RiskCohort.py", line 84, in _RiskBackpropagate
    name='partial_derivative')
  File "/home/an/python2/env/local/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/home/an/python2/env/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/an/python2/env/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1839, in orig_function
    name=name)
  File "/home/an/python2/env/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1487, in __init__
    accept_inplace)
  File "/home/an/python2/env/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 181, in std_fgraph
    update_mapping=update_mapping)
  File "/home/an/python2/env/local/lib/python2.7/site-packages/theano/gof/fg.py", line 175, in __init__
    self.__import_r__(output, reason="init")
  File "/home/an/python2/env/local/lib/python2.7/site-packages/theano/gof/fg.py", line 346, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/home/an/python2/env/local/lib/python2.7/site-packages/theano/gof/fg.py", line 391, in __import__
    raise MissingInputError(error_msg, variable=r)
theano.gof.fg.MissingInputError: Input 0 of the graph (indices start from 0), used to compute Elemwise{Cast{float64}}(mask_1), was not provided and not given a value. Use the Theano flag exception_verbosity='high', for more information on this error.

Is there any way to resolve this issue? Thank you.

**Comment by cooperlab** [comment]
It may take some time to track this down. Can you be more specific about the data and variables?

We are moving towards a TensorFlow version that will be easier to maintain in the future, and we are split between maintaining and fixing bugs on old code and developing a newer more robust package.

**Comment by utipe** [comment]
Hi,
My data is on organ transplant and we want to predict the success/risk of organ transplant patients. At the moment, we have around 400 data points but will increase in the future. Most of our variables are dummy/categorical variables e.g. diagnosis, stages, drug. On the first attempt, I forgot to take out the variable for year of transplant; with this model I can run ModelAnalysis. However, once I took out the year of transplant, I encountered the aforementioned issue.

I'm not sure if my description is enough. Please tell me if you need more information. Unfortunately, our data is confidential so I'm afraid I cannot share with you our actual data.

**Comment by cooperlab** [comment]
Did you create a new model after you removed the year variable? A trained model expects to see a certain set of variables. If you change the variable set then you need to start from the beginning and create a new model.

**Comment by utipe** [comment]
Thank you for the suggestion. Once I delete everything, re-run the model all from the start, the ModelAnalysis works out ok!

Looking forward to the TensorFlow version!

**Comment by utipe** [comment]
One more question: as far as I understand, this model's output layer is the Cox model so there's no way to get the prediction for survival time right?
